"""Auto-generate migration

Revision ID: d90997b91944
Revises: ebab57671f85
Create Date: 2024-09-02 12:29:22.514649

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d90997b91944"
down_revision: str | None = "ebab57671f85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
