version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot
    container_name: bot
    env_file:
      - ./env/docker.env
    volumes:
      - ./logs:/app/logs
      - /usr/bin:/usr/bin # Mount the /usr/bin directory
    devices:
      - /dev/vcio
    environment:
      - LD_LIBRARY_PATH=/usr/lib
    user: ${DOCKER_USER}
    command: python app.py
